name: nathacks_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none' 

# Version and build number
version: 1.0.0+1

# Dart SDK version
environment:
  sdk: ">=3.5.0 <4.0.0"

# Dependencies for your app
dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.55.0
  cupertino_icons: ^1.0.8

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter-specific configuration
flutter:
  # Ensures Material Icons font is included
  uses-material-design: true
